import "./globals.css";
import Navbar from "./components/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import CartProvider from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModal";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./components/SessionProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <CartProvider>
            <Toaster />
            <Navbar />
            <ShoppingCartModal />
            {children}
          </CartProvider>
        </Provider>
      </body>
    </html>
  );
}
